### ISSUE TITLE
v1.1 support

### ISSUE THREAD

**Issue by kirjavascript** [NieDzejkob/gbtetris#1]
Hi! This disassembly is very good.

I'd like to make some romhacks for competitive play. Unfortunately it seems everyone uses the v1.1 version of the game.

How much work is left to support it? What's left to do? I would be happy to work on it and make a PR

**Comment by meithecatte** [comment]
The biggest roadblock to making a romhack with this disassembly right now is that it is not shiftable yet – sometimes, raw addresses are used instead of labels, so if you change the code, the addresses will shift, but won't get updated everywhere.

The quick and dirty way would be to do the romhacks with binary patching methods, using the disassembly as a reference. For this, there isn't that much benefit in v1.1 support.

Depending on what your plans are, this might not be the most practical or efficient option.

To make this disassembly work for creating romhacks by just editing the source, I'd begin with doing a single pass over the code to identify pointers and eliminate baserom incbins.

Then, v1.1 support is a matter of diffing the generated 1.1 rom with the original and adding appropriate conditional compilation. Some of this has already been done. For example, the differences in the copyright screen's duration and the different placement of the serial code in ROM are handled.

I'd start with the differences that shift the entire ROM, as small differing chunks are likely to be addresses.

**Comment by kirjavascript** [comment]
To give you an idea of what I'm aiming for, I did a similar project for NES Tetris: https://github.com/kirjavascript/TetrisGYM

I dont think a lot of this would be possible (or it would be very difficult / annoying) without having a shiftable disassembly.

Identifying pointers and creating labels for them shouldn't be hard. As far as I understand it, we just have add labels for the things that point to places in ROM? 0x150-0x7FFF? Shouldn't these already have labels?

Do I need to add pointers to the symbol table and regenerate the disassembly, or is this at the point where we are just editing the asm?

Why do the baserom incbins need to be eliminated? As long as they're just data with no pointers in they should be fine to shift I would've thought? Unless there's still code there left to disassemble.
Of course, it would be still be better to have them more easily editable.

**Comment by meithecatte** [comment]
> Identifying pointers and creating labels for them shouldn't be hard. As far as I understand it, we just have add labels for the things that point to places in ROM? 0x150-0x7FFF? Shouldn't these already have labels?

You have to make it use exclusively the labels to refer to these locations, though.



> Why do the baserom incbins need to be eliminated? As long as they're just data with no pointers in they should be fine to shift I would've thought?

My thoughts there went a long the lines of "if you know the incbin well enough to know there aren't any pointers in there, removing the incbin will probably not be difficult". Not sure how close to the truth that is.



> Do I need to add pointers to the symbol table and regenerate the disassembly, or is this at the point where we are just editing the asm?

To be honest I didn't use the workflow of symbol-table-as-source-of-truth even when I started out. Might've been a mistake. You might want to build the disassembly to obtain a `.sym` file, then iterate through that. AFAIK, the tool of choice for this is [mgbdis](https://github.com/mattcurrie/mgbdis).

**Comment by kirjavascript** [comment]
thanks for the info! I think that should be all I need.

if I have anything to contribute back I'll make a PR
